# Generated by Django 5.2.1 on 2025-05-13 02:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="MemberLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="等级名称")),
                ("level", models.IntegerField(unique=True, verbose_name="等级")),
                (
                    "points_required",
                    models.IntegerField(default=0, verbose_name="所需积分"),
                ),
                (
                    "discount",
                    models.DecimalField(
                        decimal_places=2, default=1.0, max_digits=3, verbose_name="折扣率"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="等级描述")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "会员等级",
                "verbose_name_plural": "会员等级",
                "ordering": ["level"],
            },
        ),
        migrations.AlterModelOptions(
            name="withdrawalrecord",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "提现记录",
                "verbose_name_plural": "提现记录",
            },
        ),
        migrations.RemoveField(
            model_name="withdrawalrecord",
            name="account_holder",
        ),
        migrations.RemoveField(
            model_name="withdrawalrecord",
            name="bank_account",
        ),
        migrations.RemoveField(
            model_name="withdrawalrecord",
            name="bank_name",
        ),
        migrations.AddField(
            model_name="user",
            name="points",
            field=models.IntegerField(default=0, verbose_name="积分"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="average_order_value",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="平均订单金额"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="behavior_tags",
            field=models.JSONField(blank=True, default=list, verbose_name="行为标签"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="churn_risk",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=5, verbose_name="流失风险"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="customer_lifetime_value",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="客户终身价值"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="favorite_categories",
            field=models.JSONField(blank=True, default=list, verbose_name="偏好分类"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="last_purchase_date",
            field=models.DateTimeField(blank=True, null=True, verbose_name="最后购买时间"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="preferred_delivery_time",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="偏好配送时间"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="preferred_payment_method",
            field=models.CharField(
                blank=True, max_length=50, null=True, verbose_name="偏好支付方式"
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="purchase_frequency",
            field=models.IntegerField(default=0, verbose_name="购买频率"),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="user_segments",
            field=models.JSONField(blank=True, default=list, verbose_name="用户分群"),
        ),
        migrations.AddField(
            model_name="withdrawalrecord",
            name="wechat_openid",
            field=models.CharField(
                blank=True, default="", max_length=100, verbose_name="微信OpenID"
            ),
        ),
        migrations.AddField(
            model_name="withdrawalrecord",
            name="wechat_transaction_id",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="微信支付单号"
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_distributor",
            field=models.BooleanField(default=True, verbose_name="是否为分销商"),
        ),
        migrations.AlterField(
            model_name="withdrawalrecord",
            name="distributor",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="withdrawals",
                to="accounts.distributorprofile",
                verbose_name="分销商",
            ),
        ),
        migrations.AlterField(
            model_name="withdrawalrecord",
            name="processed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="processed_withdrawals",
                to=settings.AUTH_USER_MODEL,
                verbose_name="处理人",
            ),
        ),
        migrations.AlterField(
            model_name="withdrawalrecord",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待处理"),
                    ("processing", "处理中"),
                    ("success", "提现成功"),
                    ("failed", "提现失败"),
                ],
                default="pending",
                max_length=20,
                verbose_name="状态",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="member_level",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="users",
                to="accounts.memberlevel",
                verbose_name="会员等级",
            ),
        ),
    ]
