# Generated by Django 5.2.1 on 2025-05-13 03:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_withdrawalrecord_account_holder_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="withdrawalrecord",
            name="balance_returned",
            field=models.BooleanField(default=False, verbose_name="余额已返还"),
        ),
    ]
