# Generated by Django 5.2.1 on 2025-05-13 04:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0005_withdrawalrecord_balance_returned"),
    ]

    operations = [
        migrations.AlterField(
            model_name="withdrawalrecord",
            name="wechat_openid",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
