# Generated by Django 5.2.1 on 2025-05-13 09:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_alter_withdrawalrecord_wechat_openid"),
    ]

    operations = [
        migrations.AddField(
            model_name="distributorprofile",
            name="is_approved",
            field=models.BooleanField(default=False, verbose_name="是否已审核"),
        ),
    ]
