# Generated by Django 5.2.1 on 2025-05-13 02:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="commission_calculated",
            field=models.BooleanField(default=False, verbose_name="佣金已计算"),
        ),
    ]
