# Generated by Django 5.2.1 on 2025-05-13 10:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0003_alter_payment_options_remove_payment_paid_at_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="payment",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "支付记录",
                "verbose_name_plural": "支付记录",
            },
        ),
        migrations.AddField(
            model_name="order",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="优惠金额"
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_fee",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="运费"
            ),
        ),
        migrations.AddField(
            model_name="payment",
            name="paid_at",
            field=models.DateTimeField(blank=True, null=True, verbose_name="支付时间"),
        ),
        migrations.AlterField(
            model_name="cart",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="payment_method",
            field=models.CharField(
                choices=[("wechat", "微信支付"), ("alipay", "支付宝"), ("balance", "余额支付")],
                default=1,
                max_length=20,
                verbose_name="支付方式",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "待付款"),
                    ("paid", "已付款"),
                    ("shipped", "已发货"),
                    ("delivered", "已送达"),
                    ("completed", "已完成"),
                    ("cancelled", "已取消"),
                    ("refunding", "退款中"),
                    ("refunded", "已退款"),
                ],
                default="pending",
                max_length=20,
                verbose_name="订单状态",
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="total_amount",
            field=models.DecimalField(
                decimal_places=2, max_digits=10, verbose_name="总金额"
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                to=settings.AUTH_USER_MODEL,
                verbose_name="用户",
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="payment_method",
            field=models.CharField(
                choices=[("wechat", "微信支付"), ("alipay", "支付宝"), ("balance", "余额支付")],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="status",
            field=models.CharField(
                choices=[("pending", "待支付"), ("success", "支付成功"), ("failed", "支付失败")],
                default="pending",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="payment",
            name="transaction_id",
            field=models.CharField(blank=True, default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="OrderLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "待付款"),
                            ("paid", "已付款"),
                            ("shipped", "已发货"),
                            ("delivered", "已送达"),
                            ("completed", "已完成"),
                            ("cancelled", "已取消"),
                            ("refunding", "退款中"),
                            ("refunded", "已退款"),
                        ],
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "remark",
                    models.CharField(blank=True, max_length=200, verbose_name="备注"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="logs",
                        to="orders.order",
                        verbose_name="订单",
                    ),
                ),
            ],
            options={
                "verbose_name": "订单日志",
                "verbose_name_plural": "订单日志",
                "ordering": ["-created_at"],
            },
        ),
    ]
