# Generated by Django 5.2.1 on 2025-05-09 08:22

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ProductSpecification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="规格名称")),
            ],
            options={
                "verbose_name": "产品规格类型",
                "verbose_name_plural": "产品规格类型",
            },
        ),
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="分类名称")),
                (
                    "slug",
                    models.SlugField(
                        default=uuid.uuid4,
                        max_length=100,
                        unique=True,
                        verbose_name="URL标识",
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="categories/",
                        verbose_name="分类图片",
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否激活")),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="products.category",
                        verbose_name="父分类",
                    ),
                ),
            ],
            options={
                "verbose_name": "商品分类",
                "verbose_name_plural": "商品分类",
                "ordering": ["sort_order", "name"],
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200, verbose_name="产品名称")),
                (
                    "slug",
                    models.SlugField(
                        blank=True, max_length=255, unique=True, verbose_name="URL别名"
                    ),
                ),
                ("description", models.TextField(verbose_name="产品描述")),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="价格"
                    ),
                ),
                (
                    "original_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        verbose_name="原价",
                    ),
                ),
                ("stock", models.IntegerField(default=0, verbose_name="库存")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否上架")),
                (
                    "is_featured",
                    models.BooleanField(default=False, verbose_name="是否推荐"),
                ),
                (
                    "allow_distribution",
                    models.BooleanField(default=True, verbose_name="允许分销"),
                ),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=2, default=0.1, max_digits=5, verbose_name="佣金比例"
                    ),
                ),
                (
                    "secondary_commission_rate",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.05,
                        max_digits=5,
                        verbose_name="二级佣金比例",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        related_name="products",
                        to="products.category",
                        verbose_name="分类",
                    ),
                ),
            ],
            options={
                "verbose_name": "产品",
                "verbose_name_plural": "产品",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ProductImage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image", models.ImageField(upload_to="products/", verbose_name="图片")),
                ("is_primary", models.BooleanField(default=False, verbose_name="是否主图")),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="products.product",
                        verbose_name="产品",
                    ),
                ),
            ],
            options={
                "verbose_name": "产品图片",
                "verbose_name_plural": "产品图片",
                "ordering": ["sort_order"],
            },
        ),
        migrations.CreateModel(
            name="ProductVariant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "sku",
                    models.CharField(max_length=100, unique=True, verbose_name="SKU"),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="价格"
                    ),
                ),
                ("stock", models.IntegerField(default=0, verbose_name="库存")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否激活")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="variants",
                        to="products.product",
                        verbose_name="产品",
                    ),
                ),
            ],
            options={
                "verbose_name": "产品变体",
                "verbose_name_plural": "产品变体",
            },
        ),
        migrations.CreateModel(
            name="VariantSpecificationValue",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("value", models.CharField(max_length=100, verbose_name="规格值")),
                (
                    "specification",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.productspecification",
                        verbose_name="规格类型",
                    ),
                ),
                (
                    "variant",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="specifications",
                        to="products.productvariant",
                        verbose_name="产品变体",
                    ),
                ),
            ],
            options={
                "verbose_name": "变体规格值",
                "verbose_name_plural": "变体规格值",
                "unique_together": {("variant", "specification")},
            },
        ),
    ]
