# Generated by Django 5.2.1 on 2025-05-13 09:38

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "ordering": ["sort_order", "id"],
                "verbose_name": "商品分类",
                "verbose_name_plural": "商品分类",
            },
        ),
        migrations.AlterModelOptions(
            name="product",
            options={
                "ordering": ["-created_at"],
                "verbose_name": "商品",
                "verbose_name_plural": "商品",
            },
        ),
        migrations.AlterModelOptions(
            name="productimage",
            options={
                "ordering": ["sort_order", "id"],
                "verbose_name": "商品图片",
                "verbose_name_plural": "商品图片",
            },
        ),
        migrations.AlterModelOptions(
            name="productspecification",
            options={"verbose_name": "商品规格", "verbose_name_plural": "商品规格"},
        ),
        migrations.AddField(
            model_name="productspecification",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, default='2024-01-01 00:00:00', verbose_name="创建时间"
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productspecification",
            name="price_adjustment",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="价格调整"
            ),
        ),
        migrations.AddField(
            model_name="productspecification",
            name="product",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="specifications",
                to="products.product",
                verbose_name="商品",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="productspecification",
            name="stock",
            field=models.IntegerField(default=0, verbose_name="库存"),
        ),
        migrations.AddField(
            model_name="productspecification",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="更新时间"),
        ),
        migrations.AddField(
            model_name="productspecification",
            name="value",
            field=models.CharField(default='', max_length=100, verbose_name="规格值"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="category",
            name="description",
            field=models.TextField(blank=True, default='', verbose_name="分类描述"),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(default=True, verbose_name="是否启用"),
        ),
        migrations.AlterField(
            model_name="product",
            name="commission_rate",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(0),
                    django.core.validators.MaxValueValidator(100),
                ],
                verbose_name="佣金比例",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="description",
            field=models.TextField(verbose_name="商品描述"),
        ),
        migrations.AlterField(
            model_name="product",
            name="name",
            field=models.CharField(max_length=200, verbose_name="商品名称"),
        ),
        migrations.AlterField(
            model_name="product",
            name="original_price",
            field=models.DecimalField(
                decimal_places=2, default=0, max_digits=10, verbose_name="原价"
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="productimage",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="products.product",
                verbose_name="商品",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productspecification",
            unique_together={("product", "name", "value")},
        ),
        migrations.CreateModel(
            name="ProductReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "rating",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="评分",
                    ),
                ),
                ("content", models.TextField(verbose_name="评价内容")),
                (
                    "images",
                    models.JSONField(blank=True, default=list, verbose_name="评价图片"),
                ),
                (
                    "is_anonymous",
                    models.BooleanField(default=False, verbose_name="是否匿名"),
                ),
                (
                    "is_verified",
                    models.BooleanField(default=False, verbose_name="是否已购买"),
                ),
                ("likes", models.IntegerField(default=0, verbose_name="点赞数")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="products.product",
                        verbose_name="商品",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "商品评价",
                "verbose_name_plural": "商品评价",
                "ordering": ["-created_at"],
                "unique_together": {("product", "user")},
            },
        ),
        migrations.CreateModel(
            name="ReviewReply",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("content", models.TextField(verbose_name="回复内容")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "review",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="replies",
                        to="products.productreview",
                        verbose_name="评价",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="回复用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "评价回复",
                "verbose_name_plural": "评价回复",
                "ordering": ["created_at"],
            },
        ),
    ]
