# Generated by Django 5.2.1 on 2025-05-13 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0002_alter_category_options_alter_product_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="categories",
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="products.category",
                verbose_name="商品分类",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="sales",
            field=models.IntegerField(default=0, verbose_name="销量"),
        ),
        migrations.AlterField(
            model_name="productspecification",
            name="product",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="specifications",
                to="products.product",
                verbose_name="商品",
            ),
            preserve_default=False,
        ),
    ]
