# Generated by Django 5.2.1 on 2025-05-13 16:41

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Advertisement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="标题")),
                (
                    "image",
                    models.ImageField(upload_to="advertisements/", verbose_name="图片"),
                ),
                (
                    "link_url",
                    models.URLField(blank=True, null=True, verbose_name="链接地址"),
                ),
                ("allow_close", models.BooleanField(default=True, verbose_name="允许关闭")),
                ("status", models.BooleanField(default=True, verbose_name="状态")),
                ("start_time", models.DateTimeField(verbose_name="开始时间")),
                ("end_time", models.DateTimeField(verbose_name="结束时间")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "广告",
                "verbose_name_plural": "广告",
                "ordering": ["-created_at"],
            },
        ),
    ]
