# Generated by Django 5.2.1 on 2025-05-09 08:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("accounts", "0001_initial"),
        ("orders", "0001_initial"),
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DistributionLevel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="等级名称")),
                ("level", models.IntegerField(unique=True, verbose_name="等级")),
                (
                    "min_team_size",
                    models.IntegerField(default=0, verbose_name="最小团队人数"),
                ),
                (
                    "min_sales",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="最小销售额"
                    ),
                ),
                (
                    "commission_rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="佣金比例"
                    ),
                ),
                (
                    "second_level_rate",
                    models.DecimalField(
                        decimal_places=2, max_digits=5, verbose_name="二级佣金比例"
                    ),
                ),
                (
                    "benefits",
                    models.TextField(blank=True, null=True, verbose_name="权益说明"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否激活")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                ("min_orders", models.IntegerField(default=0, verbose_name="最小订单数")),
                (
                    "min_commission",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="最小佣金"
                    ),
                ),
                (
                    "upgrade_bonus",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="升级奖励"
                    ),
                ),
                (
                    "icon",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="等级图标"
                    ),
                ),
                (
                    "color",
                    models.CharField(
                        blank=True, max_length=20, null=True, verbose_name="等级颜色"
                    ),
                ),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="等级描述"),
                ),
                (
                    "privileges",
                    models.JSONField(blank=True, default=dict, verbose_name="特权列表"),
                ),
            ],
            options={
                "verbose_name": "分销商等级",
                "verbose_name_plural": "分销商等级",
                "ordering": ["level"],
            },
        ),
        migrations.CreateModel(
            name="Flash",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="活动名称")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="活动描述"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否激活")),
                ("start_time", models.DateTimeField(verbose_name="开始时间")),
                ("end_time", models.DateTimeField(verbose_name="结束时间")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "限时抢购活动",
                "verbose_name_plural": "限时抢购活动",
            },
        ),
        migrations.CreateModel(
            name="Promotion",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="活动名称")),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("banner", "轮播图"),
                            ("popup", "弹窗"),
                            ("activity", "活动页"),
                        ],
                        max_length=20,
                        verbose_name="类型",
                    ),
                ),
                (
                    "image",
                    models.ImageField(upload_to="promotions/", verbose_name="图片"),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="链接"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否激活")),
                (
                    "start_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="开始时间"),
                ),
                (
                    "end_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="结束时间"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "营销活动",
                "verbose_name_plural": "营销活动",
                "ordering": ["sort_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PromotionActivity",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="活动名称")),
                ("description", models.TextField(verbose_name="活动描述")),
                ("start_date", models.DateTimeField(verbose_name="开始时间")),
                ("end_date", models.DateTimeField(verbose_name="结束时间")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否激活")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "verbose_name": "促销活动",
                "verbose_name_plural": "促销活动",
            },
        ),
        migrations.CreateModel(
            name="Coupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="优惠码"),
                ),
                ("name", models.CharField(max_length=100, verbose_name="名称")),
                (
                    "description",
                    models.TextField(blank=True, null=True, verbose_name="描述"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[("fixed", "固定金额"), ("percentage", "百分比")],
                        max_length=20,
                        verbose_name="类型",
                    ),
                ),
                (
                    "value",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="值"
                    ),
                ),
                (
                    "min_purchase",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="最低消费"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否激活")),
                ("max_uses", models.IntegerField(default=0, verbose_name="最大使用次数")),
                ("used_count", models.IntegerField(default=0, verbose_name="已使用次数")),
                (
                    "one_per_user",
                    models.BooleanField(default=True, verbose_name="每个用户一次"),
                ),
                (
                    "start_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="开始时间"),
                ),
                (
                    "end_date",
                    models.DateTimeField(blank=True, null=True, verbose_name="结束时间"),
                ),
                (
                    "applicable_to_all",
                    models.BooleanField(default=True, verbose_name="适用于所有产品"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "categories",
                    models.ManyToManyField(
                        blank=True,
                        related_name="coupons",
                        to="products.category",
                        verbose_name="适用分类",
                    ),
                ),
                (
                    "products",
                    models.ManyToManyField(
                        blank=True,
                        related_name="coupons",
                        to="products.product",
                        verbose_name="适用产品",
                    ),
                ),
            ],
            options={
                "verbose_name": "优惠券",
                "verbose_name_plural": "优惠券",
            },
        ),
        migrations.CreateModel(
            name="CouponUsage",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "used_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="使用时间"),
                ),
                (
                    "coupon",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="usages",
                        to="promotions.coupon",
                        verbose_name="优惠券",
                    ),
                ),
                (
                    "order",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="orders.order",
                        verbose_name="订单",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "优惠券使用记录",
                "verbose_name_plural": "优惠券使用记录",
                "unique_together": {("coupon", "order")},
            },
        ),
        migrations.CreateModel(
            name="DistributionLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(max_length=20, unique=True, verbose_name="分销码"),
                ),
                ("share_count", models.IntegerField(default=0, verbose_name="分享次数")),
                ("click_count", models.IntegerField(default=0, verbose_name="点击次数")),
                ("order_count", models.IntegerField(default=0, verbose_name="订单数")),
                (
                    "total_commission",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="总佣金"
                    ),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否激活")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "distributor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="distribution_links",
                        to="accounts.distributorprofile",
                        verbose_name="分销商",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="distribution_links",
                        to="products.product",
                        verbose_name="产品",
                    ),
                ),
            ],
            options={
                "verbose_name": "分销链接",
                "verbose_name_plural": "分销链接",
                "unique_together": {("distributor", "product")},
            },
        ),
        migrations.CreateModel(
            name="FlashItem",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discount_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="抢购价"
                    ),
                ),
                ("stock_limit", models.IntegerField(default=0, verbose_name="限购数量")),
                ("sold_count", models.IntegerField(default=0, verbose_name="已售数量")),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "flash",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="items",
                        to="promotions.flash",
                        verbose_name="限时抢购活动",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="flash_items",
                        to="products.product",
                        verbose_name="产品",
                    ),
                ),
            ],
            options={
                "verbose_name": "限时抢购商品",
                "verbose_name_plural": "限时抢购商品",
                "unique_together": {("flash", "product")},
            },
        ),
        migrations.CreateModel(
            name="PromotionProduct",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "discount_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="促销价"
                    ),
                ),
                ("stock", models.IntegerField(verbose_name="促销库存")),
                ("sold_count", models.IntegerField(default=0, verbose_name="已售数量")),
                (
                    "activity",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="products",
                        to="promotions.promotionactivity",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                    ),
                ),
            ],
            options={
                "verbose_name": "促销商品",
                "verbose_name_plural": "促销商品",
                "unique_together": {("activity", "product")},
            },
        ),
        migrations.CreateModel(
            name="UserCoupon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "有效"), ("used", "已使用"), ("expired", "已过期")],
                        default="active",
                        max_length=20,
                        verbose_name="状态",
                    ),
                ),
                (
                    "used_at",
                    models.DateTimeField(blank=True, null=True, verbose_name="使用时间"),
                ),
                (
                    "acquired_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="获取时间"),
                ),
                (
                    "coupon",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_coupons",
                        to="promotions.coupon",
                        verbose_name="优惠券",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="coupons",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户优惠券",
                "verbose_name_plural": "用户优惠券",
                "unique_together": {("user", "coupon")},
            },
        ),
    ]
