# Generated by Django 5.2.1 on 2025-05-13 03:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("promotions", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PopupAd",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="广告名称")),
                (
                    "image",
                    models.ImageField(upload_to="popup_ads/", verbose_name="广告图片"),
                ),
                (
                    "url",
                    models.CharField(
                        blank=True, max_length=255, null=True, verbose_name="跳转链接"
                    ),
                ),
                ("start_time", models.DateTimeField(verbose_name="开始时间")),
                ("end_time", models.DateTimeField(verbose_name="结束时间")),
                (
                    "display_duration",
                    models.IntegerField(default=5, verbose_name="显示时长(秒)"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否激活")),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "弹窗广告",
                "verbose_name_plural": "弹窗广告",
                "ordering": ["sort_order", "-created_at"],
            },
        ),
    ]
