# Generated by Django 5.2.1 on 2025-05-13 02:37

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("products", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Alert",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="告警名称")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                ("condition", models.TextField(verbose_name="触发条件")),
                ("threshold", models.FloatField(verbose_name="阈值")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否激活")),
                (
                    "notification_channels",
                    models.JSONField(default=list, verbose_name="通知渠道"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "告警",
                "verbose_name_plural": "告警",
            },
        ),
        migrations.CreateModel(
            name="Report",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="报表名称")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                ("query", models.TextField(verbose_name="查询语句")),
                (
                    "parameters",
                    models.JSONField(blank=True, default=dict, verbose_name="参数"),
                ),
                (
                    "schedule",
                    models.CharField(blank=True, max_length=100, verbose_name="调度"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否激活")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "报表",
                "verbose_name_plural": "报表",
            },
        ),
        migrations.CreateModel(
            name="Dashboard",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="仪表盘名称")),
                ("description", models.TextField(blank=True, verbose_name="描述")),
                ("layout", models.JSONField(default=dict, verbose_name="布局")),
                ("is_public", models.BooleanField(default=False, verbose_name="是否公开")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="创建者",
                    ),
                ),
            ],
            options={
                "verbose_name": "仪表盘",
                "verbose_name_plural": "仪表盘",
            },
        ),
        migrations.CreateModel(
            name="DataPoint",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, verbose_name="指标名称")),
                ("value", models.FloatField(verbose_name="指标值")),
                (
                    "timestamp",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="时间戳"
                    ),
                ),
                ("category", models.CharField(max_length=50, verbose_name="分类")),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="元数据"),
                ),
            ],
            options={
                "verbose_name": "数据点",
                "verbose_name_plural": "数据点",
                "indexes": [
                    models.Index(
                        fields=["name", "timestamp"], name="analytics_d_name_d8bc45_idx"
                    ),
                    models.Index(
                        fields=["category", "timestamp"],
                        name="analytics_d_categor_e56b2d_idx",
                    ),
                ],
            },
        ),
        migrations.CreateModel(
            name="SalesAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="日期")),
                (
                    "total_sales",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="总销售额"
                    ),
                ),
                ("order_count", models.IntegerField(verbose_name="订单数")),
                (
                    "average_order_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="平均订单金额"
                    ),
                ),
                ("product_count", models.IntegerField(verbose_name="商品数")),
                ("customer_count", models.IntegerField(verbose_name="客户数")),
                (
                    "refund_amount",
                    models.DecimalField(
                        decimal_places=2, default=0, max_digits=10, verbose_name="退款金额"
                    ),
                ),
                ("refund_count", models.IntegerField(default=0, verbose_name="退款数")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "销售分析",
                "verbose_name_plural": "销售分析",
                "indexes": [
                    models.Index(fields=["date"], name="analytics_s_date_715b65_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="UserAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="日期")),
                ("new_users", models.IntegerField(verbose_name="新增用户")),
                ("active_users", models.IntegerField(verbose_name="活跃用户")),
                ("returning_users", models.IntegerField(verbose_name="回访用户")),
                ("churned_users", models.IntegerField(verbose_name="流失用户")),
                ("total_users", models.IntegerField(verbose_name="总用户数")),
                ("user_segments", models.JSONField(default=dict, verbose_name="用户分群")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
            ],
            options={
                "verbose_name": "用户分析",
                "verbose_name_plural": "用户分析",
                "indexes": [
                    models.Index(fields=["date"], name="analytics_u_date_09f122_idx")
                ],
            },
        ),
        migrations.CreateModel(
            name="ProductAnalytics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField(verbose_name="日期")),
                ("views", models.IntegerField(verbose_name="浏览量")),
                ("sales", models.IntegerField(verbose_name="销量")),
                (
                    "revenue",
                    models.DecimalField(
                        decimal_places=2, max_digits=10, verbose_name="收入"
                    ),
                ),
                ("conversion_rate", models.FloatField(verbose_name="转化率")),
                ("average_rating", models.FloatField(verbose_name="平均评分")),
                ("review_count", models.IntegerField(verbose_name="评价数")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="products.product",
                        verbose_name="商品",
                    ),
                ),
            ],
            options={
                "verbose_name": "商品分析",
                "verbose_name_plural": "商品分析",
                "indexes": [
                    models.Index(
                        fields=["date", "product"], name="analytics_p_date_c15a74_idx"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="UserBehavior",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("action", models.CharField(max_length=50, verbose_name="行为")),
                ("object_id", models.PositiveIntegerField()),
                (
                    "metadata",
                    models.JSONField(blank=True, default=dict, verbose_name="元数据"),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户行为",
                "verbose_name_plural": "用户行为",
                "indexes": [
                    models.Index(
                        fields=["user", "action", "created_at"],
                        name="analytics_u_user_id_087891_idx",
                    )
                ],
            },
        ),
    ]
