# Generated by Django 5.2.1 on 2025-05-13 04:29

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="MiniProgramSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("app_name", models.CharField(max_length=100, verbose_name="小程序名称")),
                ("app_id", models.CharField(max_length=100, verbose_name="AppID")),
                (
                    "app_secret",
                    models.CharField(max_length=100, verbose_name="AppSecret"),
                ),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "小程序设置",
                "verbose_name_plural": "小程序设置",
            },
        ),
    ]
