# Generated by Django 5.2.1 on 2025-05-13 09:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("dashboard", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Advertisement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="广告标题")),
                (
                    "image",
                    models.ImageField(upload_to="advertisements/", verbose_name="广告图片"),
                ),
                ("link", models.URLField(blank=True, null=True, verbose_name="链接地址")),
                ("start_time", models.DateTimeField(verbose_name="开始时间")),
                ("end_time", models.DateTimeField(verbose_name="结束时间")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("home_popup", "首页弹窗"),
                            ("home_banner", "首页轮播"),
                            ("category_banner", "分类页横幅"),
                        ],
                        max_length=50,
                        verbose_name="显示位置",
                    ),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "广告管理",
                "verbose_name_plural": "广告管理",
                "ordering": ["-sort_order", "-created_at"],
            },
        ),
        migrations.CreateModel(
            name="HomePageSettings",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100, verbose_name="网站标题")),
                (
                    "logo",
                    models.ImageField(upload_to="settings/", verbose_name="网站Logo"),
                ),
                ("footer_text", models.TextField(blank=True, verbose_name="页脚文本")),
                ("announcement", models.TextField(blank=True, verbose_name="公告内容")),
                (
                    "is_announcement_active",
                    models.BooleanField(default=False, verbose_name="是否显示公告"),
                ),
                (
                    "theme_color",
                    models.CharField(
                        default="#4CAF50", max_length=20, verbose_name="主题色"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
            ],
            options={
                "verbose_name": "首页设置",
                "verbose_name_plural": "首页设置",
            },
        ),
        migrations.CreateModel(
            name="NavigationMenu",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, verbose_name="菜单名称")),
                ("url", models.CharField(max_length=200, verbose_name="链接地址")),
                (
                    "icon",
                    models.CharField(blank=True, max_length=50, verbose_name="图标"),
                ),
                ("sort_order", models.IntegerField(default=0, verbose_name="排序")),
                ("is_active", models.BooleanField(default=True, verbose_name="是否启用")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="children",
                        to="dashboard.navigationmenu",
                        verbose_name="父级菜单",
                    ),
                ),
            ],
            options={
                "verbose_name": "导航菜单",
                "verbose_name_plural": "导航菜单",
                "ordering": ["sort_order", "id"],
            },
        ),
    ]
