# Generated by Django 5.2.1 on 2025-05-13 10:22

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("dashboard", "0002_advertisement_homepagesettings_navigationmenu"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AdminLog",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "action",
                    models.CharField(
                        choices=[
                            ("create", "创建"),
                            ("update", "更新"),
                            ("delete", "删除"),
                            ("login", "登录"),
                            ("logout", "登出"),
                            ("export", "导出"),
                            ("import", "导入"),
                            ("other", "其他"),
                        ],
                        max_length=20,
                        verbose_name="操作类型",
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="操作对象ID"
                    ),
                ),
                (
                    "object_repr",
                    models.CharField(blank=True, max_length=200, verbose_name="操作对象"),
                ),
                ("change_message", models.TextField(blank=True, verbose_name="变更信息")),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        blank=True, null=True, verbose_name="IP地址"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="操作时间"),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="contenttypes.contenttype",
                        verbose_name="操作对象类型",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="操作人",
                    ),
                ),
            ],
            options={
                "verbose_name": "操作日志",
                "verbose_name_plural": "操作日志",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="ExportRecord",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("model_name", models.CharField(max_length=100, verbose_name="模型名称")),
                (
                    "format",
                    models.CharField(
                        choices=[("xlsx", "Excel"), ("csv", "CSV"), ("pdf", "PDF")],
                        max_length=10,
                        verbose_name="导出格式",
                    ),
                ),
                (
                    "filters",
                    models.JSONField(blank=True, default=dict, verbose_name="筛选条件"),
                ),
                ("file_path", models.CharField(max_length=255, verbose_name="文件路径")),
                ("file_size", models.IntegerField(default=0, verbose_name="文件大小")),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="导出时间"),
                ),
                (
                    "is_deleted",
                    models.BooleanField(default=False, verbose_name="是否已删除"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="导出人",
                    ),
                ),
            ],
            options={
                "verbose_name": "导出记录",
                "verbose_name_plural": "导出记录",
                "ordering": ["-created_at"],
            },
        ),
    ]
